/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectRole = IDL.Variant({
  'admin' : IDL.Null,
  'editor' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
  'projectId' : IDL.Nat,
});
export const AuditLog = IDL.Record({
  'entity' : IDL.Text,
  'principal' : IDL.Principal,
  'action' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const Collection = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Nat,
  'assetIds' : IDL.Vec(IDL.Nat),
});
export const FileMetadata = IDL.Record({
  'id' : IDL.Nat,
  'assetId' : IDL.Opt(IDL.Nat),
  'hash' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'projectId' : IDL.Nat,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const MergeOperation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'completedAt' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'sourceAssetIds' : IDL.Vec(IDL.Nat),
  'targetAssetId' : IDL.Nat,
  'projectId' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : IDL.Opt(Time),
});
export const ProjectMember = IDL.Record({
  'member' : IDL.Principal,
  'role' : ProjectRole,
  'addedAt' : IDL.Int,
  'addedBy' : IDL.Principal,
  'projectId' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'assetId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'projectId' : IDL.Nat,
});
export const Token = IDL.Record({
  'id' : IDL.Nat,
  'metadata' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'mintedAt' : IDL.Int,
  'mintedBy' : IDL.Principal,
  'projectId' : IDL.Nat,
});
export const TransitionRule = IDL.Record({
  'id' : IDL.Nat,
  'toStatus' : IDL.Text,
  'name' : IDL.Text,
  'fromStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'projectId' : IDL.Nat,
  'conditions' : IDL.Text,
});
export const ValidationRule = IDL.Record({
  'id' : IDL.Nat,
  'ruleType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'projectId' : IDL.Nat,
  'conditions' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProjectMember' : IDL.Func([IDL.Nat, IDL.Principal, ProjectRole], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createCollection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Nat], [], []),
  'deleteCollection' : IDL.Func([IDL.Nat], [], []),
  'deleteFileMetadata' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
  'getAuditLogs' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(AuditLog) })],
      [],
    ),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
  'getFileMetadata' : IDL.Func([IDL.Nat], [IDL.Opt(FileMetadata)], ['query']),
  'getMergeOperation' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MergeOperation)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectMember' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Opt(ProjectMember)],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getToken' : IDL.Func([IDL.Nat], [IDL.Opt(Token)], ['query']),
  'getTransitionRule' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TransitionRule)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidationRule' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ValidationRule)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'listAssetsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
  'listCollectionsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Collection)],
      ['query'],
    ),
  'listFileMetadataByAsset' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'listMembersByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProjectMember)],
      ['query'],
    ),
  'listMergeOperationsByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MergeOperation)],
      ['query'],
    ),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listTasksByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'listTokensByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Token)], ['query']),
  'listTransitionRulesByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TransitionRule)],
      ['query'],
    ),
  'listValidationRulesByProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ValidationRule)],
      ['query'],
    ),
  'mintToken' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Token, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'removeProjectMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfAssignAdmin' : IDL.Func([IDL.Nat], [], []),
  'storeFileMetadata' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateCollection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateProjectMemberRole' : IDL.Func(
      [IDL.Nat, IDL.Principal, ProjectRole],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectRole = IDL.Variant({
    'admin' : IDL.Null,
    'editor' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
    'projectId' : IDL.Nat,
  });
  const AuditLog = IDL.Record({
    'entity' : IDL.Text,
    'principal' : IDL.Principal,
    'action' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const Collection = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Nat,
    'assetIds' : IDL.Vec(IDL.Nat),
  });
  const FileMetadata = IDL.Record({
    'id' : IDL.Nat,
    'assetId' : IDL.Opt(IDL.Nat),
    'hash' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'projectId' : IDL.Nat,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const MergeOperation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'completedAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'sourceAssetIds' : IDL.Vec(IDL.Nat),
    'targetAssetId' : IDL.Nat,
    'projectId' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : IDL.Opt(Time),
  });
  const ProjectMember = IDL.Record({
    'member' : IDL.Principal,
    'role' : ProjectRole,
    'addedAt' : IDL.Int,
    'addedBy' : IDL.Principal,
    'projectId' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'assetId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'projectId' : IDL.Nat,
  });
  const Token = IDL.Record({
    'id' : IDL.Nat,
    'metadata' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'mintedAt' : IDL.Int,
    'mintedBy' : IDL.Principal,
    'projectId' : IDL.Nat,
  });
  const TransitionRule = IDL.Record({
    'id' : IDL.Nat,
    'toStatus' : IDL.Text,
    'name' : IDL.Text,
    'fromStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'projectId' : IDL.Nat,
    'conditions' : IDL.Text,
  });
  const ValidationRule = IDL.Record({
    'id' : IDL.Nat,
    'ruleType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'projectId' : IDL.Nat,
    'conditions' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProjectMember' : IDL.Func(
        [IDL.Nat, IDL.Principal, ProjectRole],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createCollection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createProject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Nat], [], []),
    'deleteCollection' : IDL.Func([IDL.Nat], [], []),
    'deleteFileMetadata' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAsset' : IDL.Func([IDL.Nat], [IDL.Opt(Asset)], ['query']),
    'getAuditLogs' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(AuditLog) })],
        [],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Collection)], ['query']),
    'getFileMetadata' : IDL.Func([IDL.Nat], [IDL.Opt(FileMetadata)], ['query']),
    'getMergeOperation' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MergeOperation)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectMember' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Opt(ProjectMember)],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getToken' : IDL.Func([IDL.Nat], [IDL.Opt(Token)], ['query']),
    'getTransitionRule' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TransitionRule)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidationRule' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ValidationRule)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'listAssetsByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Asset)], ['query']),
    'listCollectionsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Collection)],
        ['query'],
      ),
    'listFileMetadataByAsset' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'listMembersByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProjectMember)],
        ['query'],
      ),
    'listMergeOperationsByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MergeOperation)],
        ['query'],
      ),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listTasksByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'listTokensByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Token)], ['query']),
    'listTransitionRulesByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TransitionRule)],
        ['query'],
      ),
    'listValidationRulesByProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ValidationRule)],
        ['query'],
      ),
    'mintToken' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Token, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'removeProjectMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfAssignAdmin' : IDL.Func([IDL.Nat], [], []),
    'storeFileMetadata' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateAsset' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateCollection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateProjectMemberRole' : IDL.Func(
        [IDL.Nat, IDL.Principal, ProjectRole],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };