/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : [] | [Time],
  'projectId' : bigint,
}
export interface AuditLog {
  'entity' : string,
  'principal' : Principal,
  'action' : string,
  'timestamp' : bigint,
}
export interface Collection {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'updatedAt' : bigint,
  'projectId' : bigint,
  'assetIds' : Array<bigint>,
}
export interface FileMetadata {
  'id' : bigint,
  'assetId' : [] | [bigint],
  'hash' : string,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'projectId' : bigint,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface MergeOperation {
  'id' : bigint,
  'status' : string,
  'completedAt' : [] | [bigint],
  'createdAt' : bigint,
  'createdBy' : Principal,
  'sourceAssetIds' : Array<bigint>,
  'targetAssetId' : bigint,
  'projectId' : bigint,
}
export interface PlatformConfig {
  'tagline' : string,
  'accentColor' : string,
  'platformName' : string,
}
export interface Project {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : [] | [Time],
}
export interface ProjectMember {
  'member' : Principal,
  'role' : ProjectRole,
  'addedAt' : bigint,
  'addedBy' : Principal,
  'projectId' : bigint,
}
export type ProjectRole = { 'admin' : null } |
  { 'editor' : null } |
  { 'viewer' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'pro' : null } |
  { 'starter' : null } |
  { 'free' : null };
export interface Task {
  'id' : bigint,
  'status' : string,
  'assignedTo' : [] | [Principal],
  'assetId' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'updatedAt' : bigint,
  'projectId' : bigint,
}
export type Time = bigint;
export interface Token {
  'id' : bigint,
  'metadata' : string,
  'name' : string,
  'description' : string,
  'mintedAt' : bigint,
  'mintedBy' : Principal,
  'projectId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TransitionRule {
  'id' : bigint,
  'toStatus' : string,
  'name' : string,
  'fromStatus' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'projectId' : bigint,
  'conditions' : string,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubscription {
  'principal' : Principal,
  'tier' : SubscriptionTier,
  'updatedAt' : bigint,
}
export interface ValidationRule {
  'id' : bigint,
  'ruleType' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'projectId' : bigint,
  'conditions' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProjectMember' : ActorMethod<[bigint, Principal, ProjectRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAsset' : ActorMethod<[bigint, string, string], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCollection' : ActorMethod<
    [bigint, string, string, Array<bigint>],
    bigint
  >,
  'createProject' : ActorMethod<
    [string, string],
    { 'Ok' : bigint } |
      { 'Err' : string }
  >,
  'createTask' : ActorMethod<
    [bigint, [] | [bigint], string, string, string, [] | [Principal]],
    bigint
  >,
  'deleteAsset' : ActorMethod<[bigint], undefined>,
  'deleteCollection' : ActorMethod<[bigint], undefined>,
  'deleteFileMetadata' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAsset' : ActorMethod<[bigint], [] | [Asset]>,
  'getAuditLogs' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'entries' : Array<AuditLog> }
  >,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollection' : ActorMethod<[bigint], [] | [Collection]>,
  'getFileMetadata' : ActorMethod<[bigint], [] | [FileMetadata]>,
  'getMergeOperation' : ActorMethod<[bigint], [] | [MergeOperation]>,
  'getMySubscription' : ActorMethod<[], [] | [UserSubscription]>,
  'getPlatformConfig' : ActorMethod<[], [] | [PlatformConfig]>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectCountForCaller' : ActorMethod<[], bigint>,
  'getProjectMember' : ActorMethod<[bigint, Principal], [] | [ProjectMember]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getToken' : ActorMethod<[bigint], [] | [Token]>,
  'getTransitionRule' : ActorMethod<[bigint], [] | [TransitionRule]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidationRule' : ActorMethod<[bigint], [] | [ValidationRule]>,
  'handleStripePaymentCompleted' : ActorMethod<
    [SubscriptionTier, Principal],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAssets' : ActorMethod<[], Array<Asset>>,
  'listAssetsByProject' : ActorMethod<[bigint], Array<Asset>>,
  'listCollectionsByProject' : ActorMethod<[bigint], Array<Collection>>,
  'listFileMetadataByAsset' : ActorMethod<[bigint], Array<FileMetadata>>,
  'listMembersByProject' : ActorMethod<[bigint], Array<ProjectMember>>,
  'listMergeOperationsByProject' : ActorMethod<[bigint], Array<MergeOperation>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listTasksByProject' : ActorMethod<[bigint], Array<Task>>,
  'listTokensByProject' : ActorMethod<[bigint], Array<Token>>,
  'listTransitionRulesByProject' : ActorMethod<[bigint], Array<TransitionRule>>,
  'listValidationRulesByProject' : ActorMethod<[bigint], Array<ValidationRule>>,
  'mintToken' : ActorMethod<
    [bigint, string, string, string],
    { 'Ok' : Token } |
      { 'Err' : string }
  >,
  'registerUser' : ActorMethod<[string], bigint>,
  'removeProjectMember' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfAssignAdmin' : ActorMethod<[], undefined>,
  'setPlatformConfig' : ActorMethod<
    [PlatformConfig],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storeFileMetadata' : ActorMethod<
    [bigint, [] | [bigint], string, string, bigint, string],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAsset' : ActorMethod<[bigint, string, string], undefined>,
  'updateCollection' : ActorMethod<
    [bigint, string, string, Array<bigint>],
    undefined
  >,
  'updateProject' : ActorMethod<[bigint, string, string], undefined>,
  'updateProjectMemberRole' : ActorMethod<
    [bigint, Principal, ProjectRole],
    undefined
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, string, [] | [Principal]],
    undefined
  >,
  'upgradeSubscription' : ActorMethod<
    [SubscriptionTier],
    { 'Ok' : null } |
      { 'Err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];