/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransitionRule {
    id: bigint;
    toStatus: string;
    name: string;
    fromStatus: string;
    createdAt: bigint;
    createdBy: Principal;
    projectId: bigint;
    conditions: string;
}
export interface ProjectMember {
    member: Principal;
    role: ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
}
export type Time = bigint;
export interface FileMetadata {
    id: bigint;
    assetId?: bigint;
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface MergeOperation {
    id: bigint;
    status: string;
    completedAt?: bigint;
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
}
export interface Task {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    assetId?: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
}
export interface Collection {
    id: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
    assetIds: Array<bigint>;
}
export interface Asset {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
    projectId: bigint;
}
export interface Token {
    id: bigint;
    metadata: string;
    name: string;
    description: string;
    mintedAt: bigint;
    mintedBy: Principal;
    projectId: bigint;
}
export interface ValidationRule {
    id: bigint;
    ruleType: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    projectId: bigint;
    conditions: string;
}
export interface Project {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
}
export interface UserProfile {
    username: string;
    name: string;
}
export enum ProjectRole {
    admin = "admin",
    editor = "editor",
    viewer = "viewer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProjectMember(projectId: bigint, member: Principal, role: ProjectRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAsset(projectId: bigint, name: string, description: string): Promise<bigint>;
    createCollection(projectId: bigint, name: string, description: string, assetIds: Array<bigint>): Promise<bigint>;
    createProject(name: string, description: string): Promise<bigint>;
    createTask(projectId: bigint, assetId: bigint | null, name: string, description: string, status: string, assignedTo: Principal | null): Promise<bigint>;
    deleteAsset(id: bigint): Promise<void>;
    deleteCollection(id: bigint): Promise<void>;
    deleteFileMetadata(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    getAsset(id: bigint): Promise<Asset | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollection(id: bigint): Promise<Collection | null>;
    getFileMetadata(id: bigint): Promise<FileMetadata | null>;
    getMergeOperation(id: bigint): Promise<MergeOperation | null>;
    getProject(id: bigint): Promise<Project | null>;
    getProjectMember(projectId: bigint, member: Principal): Promise<ProjectMember | null>;
    getTask(id: bigint): Promise<Task | null>;
    getToken(tokenId: bigint): Promise<Token | null>;
    getTransitionRule(id: bigint): Promise<TransitionRule | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValidationRule(id: bigint): Promise<ValidationRule | null>;
    isCallerAdmin(): Promise<boolean>;
    listAssets(): Promise<Array<Asset>>;
    listAssetsByProject(projectId: bigint): Promise<Array<Asset>>;
    listCollectionsByProject(projectId: bigint): Promise<Array<Collection>>;
    listFileMetadataByAsset(assetId: bigint): Promise<Array<FileMetadata>>;
    listMembersByProject(projectId: bigint): Promise<Array<ProjectMember>>;
    listMergeOperationsByProject(projectId: bigint): Promise<Array<MergeOperation>>;
    listProjects(): Promise<Array<Project>>;
    listTasksByProject(projectId: bigint): Promise<Array<Task>>;
    listTokensByProject(projectId: bigint): Promise<Array<Token>>;
    listTransitionRulesByProject(projectId: bigint): Promise<Array<TransitionRule>>;
    listValidationRulesByProject(projectId: bigint): Promise<Array<ValidationRule>>;
    mintToken(projectId: bigint, name: string, description: string, metadata: string): Promise<{
        __kind__: "ok";
        ok: Token;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(username: string): Promise<bigint>;
    removeProjectMember(projectId: bigint, member: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeFileMetadata(projectId: bigint, assetId: bigint | null, filename: string, mimeType: string, size: bigint, hash: string): Promise<bigint>;
    updateAsset(id: bigint, name: string, description: string): Promise<void>;
    updateCollection(id: bigint, name: string, description: string, assetIds: Array<bigint>): Promise<void>;
    updateProject(id: bigint, name: string, description: string): Promise<void>;
    updateProjectMemberRole(projectId: bigint, member: Principal, newRole: ProjectRole): Promise<void>;
    updateTask(id: bigint, name: string, description: string, status: string, assignedTo: Principal | null): Promise<void>;
}
import type { Asset as _Asset, Collection as _Collection, FileMetadata as _FileMetadata, MergeOperation as _MergeOperation, Project as _Project, ProjectMember as _ProjectMember, ProjectRole as _ProjectRole, Task as _Task, Time as _Time, Token as _Token, TransitionRule as _TransitionRule, UserProfile as _UserProfile, UserRole as _UserRole, ValidationRule as _ValidationRule } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProjectMember(arg0: bigint, arg1: Principal, arg2: ProjectRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAsset(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAsset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAsset(arg0, arg1, arg2);
            return result;
        }
    }
    async createCollection(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createTask(arg0: bigint, arg1: bigint | null, arg2: string, arg3: string, arg4: string, arg5: Principal | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteCollection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteFileMetadata(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileMetadata(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAsset(arg0: bigint): Promise<Asset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: bigint): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileMetadata(arg0: bigint): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMergeOperation(arg0: bigint): Promise<MergeOperation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMergeOperation(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMergeOperation(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectMember(arg0: bigint, arg1: Principal): Promise<ProjectMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectMember(arg0, arg1);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectMember(arg0, arg1);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToken(arg0: bigint): Promise<Token | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToken(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToken(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransitionRule(arg0: bigint): Promise<TransitionRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransitionRule(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransitionRule(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidationRule(arg0: bigint): Promise<ValidationRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidationRule(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidationRule(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssets();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssets();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssetsByProject(arg0: bigint): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssetsByProject(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssetsByProject(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCollectionsByProject(arg0: bigint): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollectionsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollectionsByProject(arg0);
            return result;
        }
    }
    async listFileMetadataByAsset(arg0: bigint): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileMetadataByAsset(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileMetadataByAsset(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMembersByProject(arg0: bigint): Promise<Array<ProjectMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembersByProject(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembersByProject(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMergeOperationsByProject(arg0: bigint): Promise<Array<MergeOperation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMergeOperationsByProject(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMergeOperationsByProject(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByProject(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByProject(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByProject(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTokensByProject(arg0: bigint): Promise<Array<Token>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTokensByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTokensByProject(arg0);
            return result;
        }
    }
    async listTransitionRulesByProject(arg0: bigint): Promise<Array<TransitionRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransitionRulesByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransitionRulesByProject(arg0);
            return result;
        }
    }
    async listValidationRulesByProject(arg0: bigint): Promise<Array<ValidationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listValidationRulesByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listValidationRulesByProject(arg0);
            return result;
        }
    }
    async mintToken(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: Token;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.mintToken(arg0, arg1, arg2, arg3);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintToken(arg0, arg1, arg2, arg3);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async removeProjectMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProjectMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProjectMember(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async storeFileMetadata(arg0: bigint, arg1: bigint | null, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeFileMetadata(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeFileMetadata(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateAsset(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCollection(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProjectMemberRole(arg0: bigint, arg1: Principal, arg2: ProjectRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_Asset_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_FileMetadata_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): FileMetadata {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MergeOperation_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MergeOperation): MergeOperation {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectMember_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMember): ProjectMember {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRole): ProjectRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): FileMetadata | null {
    return value.length === 0 ? null : from_candid_FileMetadata_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MergeOperation]): MergeOperation | null {
    return value.length === 0 ? null : from_candid_MergeOperation_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectMember]): ProjectMember | null {
    return value.length === 0 ? null : from_candid_ProjectMember_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Token]): Token | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransitionRule]): TransitionRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ValidationRule]): ValidationRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : from_candid_Asset_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assetId: [] | [bigint];
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): {
    id: bigint;
    assetId?: bigint;
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        assetId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.assetId)),
        hash: value.hash,
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        projectId: value.projectId,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    completedAt: [] | [bigint];
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
}): {
    id: bigint;
    status: string;
    completedAt?: bigint;
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        completedAt: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.completedAt)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        sourceAssetIds: value.sourceAssetIds,
        targetAssetId: value.targetAssetId,
        projectId: value.projectId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: [] | [_Time];
}): {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.updatedAt))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: Principal;
    role: _ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
}): {
    member: Principal;
    role: ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
} {
    return {
        member: value.member,
        role: from_candid_ProjectRole_n29(_uploadFile, _downloadFile, value.role),
        addedAt: value.addedAt,
        addedBy: value.addedBy,
        projectId: value.projectId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    assignedTo: [] | [Principal];
    assetId: [] | [bigint];
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
}): {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    assetId?: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        assignedTo: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.assignedTo)),
        assetId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.assetId)),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: value.projectId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: [] | [_Time];
    projectId: bigint;
}): {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
    projectId: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.updatedAt)),
        projectId: value.projectId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    editor: null;
} | {
    viewer: null;
}): ProjectRole {
    return "admin" in value ? ProjectRole.admin : "editor" in value ? ProjectRole.editor : "viewer" in value ? ProjectRole.viewer : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Token;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Token;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Array<FileMetadata> {
    return value.map((x)=>from_candid_FileMetadata_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectMember>): Array<ProjectMember> {
    return value.map((x)=>from_candid_ProjectMember_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MergeOperation>): Array<MergeOperation> {
    return value.map((x)=>from_candid_MergeOperation_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n32(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): _ProjectRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): {
    admin: null;
} | {
    editor: null;
} | {
    viewer: null;
} {
    return value == ProjectRole.admin ? {
        admin: null
    } : value == ProjectRole.editor ? {
        editor: null
    } : value == ProjectRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
