/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransitionRule {
    id: bigint;
    toStatus: string;
    name: string;
    fromStatus: string;
    createdAt: bigint;
    createdBy: Principal;
    projectId: bigint;
    conditions: string;
}
export interface ProjectMember {
    member: Principal;
    role: ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface FileMetadata {
    id: bigint;
    assetId?: bigint;
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface MergeOperation {
    id: bigint;
    status: string;
    completedAt?: bigint;
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
}
export interface AuditLog {
    entity: string;
    principal: Principal;
    action: string;
    timestamp: bigint;
}
export interface Task {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    assetId?: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
}
export interface PlatformConfig {
    tagline: string;
    accentColor: string;
    platformName: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Collection {
    id: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
    assetIds: Array<bigint>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Asset {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
    projectId: bigint;
}
export interface Token {
    id: bigint;
    metadata: string;
    name: string;
    description: string;
    mintedAt: bigint;
    mintedBy: Principal;
    projectId: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface UserSubscription {
    principal: Principal;
    tier: SubscriptionTier;
    updatedAt: bigint;
}
export interface ValidationRule {
    id: bigint;
    ruleType: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    projectId: bigint;
    conditions: string;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    username: string;
    name: string;
}
export interface Project {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
}
export enum ProjectRole {
    admin = "admin",
    editor = "editor",
    viewer = "viewer"
}
export enum SubscriptionTier {
    pro = "pro",
    starter = "starter",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProjectMember(projectId: bigint, member: Principal, role: ProjectRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAsset(projectId: bigint, name: string, description: string): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCollection(projectId: bigint, name: string, description: string, assetIds: Array<bigint>): Promise<bigint>;
    createProject(name: string, description: string): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    createTask(projectId: bigint, assetId: bigint | null, name: string, description: string, status: string, assignedTo: Principal | null): Promise<bigint>;
    deleteAsset(id: bigint): Promise<void>;
    deleteCollection(id: bigint): Promise<void>;
    deleteFileMetadata(id: bigint): Promise<void>;
    deleteProject(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    getAsset(id: bigint): Promise<Asset | null>;
    getAuditLogs(page: bigint, pageSize: bigint): Promise<{
        total: bigint;
        entries: Array<AuditLog>;
    }>;
    getCallerRole(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollection(id: bigint): Promise<Collection | null>;
    getFileMetadata(id: bigint): Promise<FileMetadata | null>;
    getMergeOperation(id: bigint): Promise<MergeOperation | null>;
    getMySubscription(): Promise<UserSubscription | null>;
    getPlatformConfig(): Promise<PlatformConfig | null>;
    getProject(id: bigint): Promise<Project | null>;
    getProjectCountForCaller(): Promise<bigint>;
    getProjectMember(projectId: bigint, member: Principal): Promise<ProjectMember | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTask(id: bigint): Promise<Task | null>;
    getToken(tokenId: bigint): Promise<Token | null>;
    getTransitionRule(id: bigint): Promise<TransitionRule | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValidationRule(id: bigint): Promise<ValidationRule | null>;
    handleStripePaymentCompleted(tier: SubscriptionTier, user: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAssets(): Promise<Array<Asset>>;
    listAssetsByProject(projectId: bigint): Promise<Array<Asset>>;
    listCollectionsByProject(projectId: bigint): Promise<Array<Collection>>;
    listFileMetadataByAsset(assetId: bigint): Promise<Array<FileMetadata>>;
    listMembersByProject(projectId: bigint): Promise<Array<ProjectMember>>;
    listMergeOperationsByProject(projectId: bigint): Promise<Array<MergeOperation>>;
    listProjects(): Promise<Array<Project>>;
    listTasksByProject(projectId: bigint): Promise<Array<Task>>;
    listTokensByProject(projectId: bigint): Promise<Array<Token>>;
    listTransitionRulesByProject(projectId: bigint): Promise<Array<TransitionRule>>;
    listValidationRulesByProject(projectId: bigint): Promise<Array<ValidationRule>>;
    mintToken(projectId: bigint, name: string, description: string, metadata: string): Promise<{
        __kind__: "Ok";
        Ok: Token;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    registerUser(username: string): Promise<bigint>;
    removeProjectMember(projectId: bigint, member: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    selfAssignAdmin(): Promise<void>;
    setPlatformConfig(config: PlatformConfig): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    storeFileMetadata(projectId: bigint, assetId: bigint | null, filename: string, mimeType: string, size: bigint, hash: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAsset(id: bigint, name: string, description: string): Promise<void>;
    updateCollection(id: bigint, name: string, description: string, assetIds: Array<bigint>): Promise<void>;
    updateProject(id: bigint, name: string, description: string): Promise<void>;
    updateProjectMemberRole(projectId: bigint, member: Principal, newRole: ProjectRole): Promise<void>;
    updateTask(id: bigint, name: string, description: string, status: string, assignedTo: Principal | null): Promise<void>;
    upgradeSubscription(tier: SubscriptionTier): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }>;
}
import type { Asset as _Asset, Collection as _Collection, FileMetadata as _FileMetadata, MergeOperation as _MergeOperation, PlatformConfig as _PlatformConfig, Project as _Project, ProjectMember as _ProjectMember, ProjectRole as _ProjectRole, StripeSessionStatus as _StripeSessionStatus, SubscriptionTier as _SubscriptionTier, Task as _Task, Time as _Time, Token as _Token, TransitionRule as _TransitionRule, UserProfile as _UserProfile, UserRole as _UserRole, UserSubscription as _UserSubscription, ValidationRule as _ValidationRule } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProjectMember(arg0: bigint, arg1: Principal, arg2: ProjectRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectMember(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAsset(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAsset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAsset(arg0, arg1, arg2);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCollection(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string): Promise<{
        __kind__: "Ok";
        Ok: bigint;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: bigint, arg1: bigint | null, arg2: string, arg3: string, arg4: string, arg5: Principal | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteAsset(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return result;
        }
    }
    async deleteCollection(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteFileMetadata(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileMetadata(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAsset(arg0: bigint): Promise<Asset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAsset(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAsset(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(arg0: bigint, arg1: bigint): Promise<{
        total: bigint;
        entries: Array<AuditLog>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0, arg1);
            return result;
        }
    }
    async getCallerRole(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: bigint): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileMetadata(arg0: bigint): Promise<FileMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileMetadata(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileMetadata(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMergeOperation(arg0: bigint): Promise<MergeOperation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMergeOperation(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMergeOperation(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubscription(): Promise<UserSubscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformConfig(): Promise<PlatformConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformConfig();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformConfig();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectCountForCaller(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectCountForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectCountForCaller();
            return result;
        }
    }
    async getProjectMember(arg0: bigint, arg1: Principal): Promise<ProjectMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectMember(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectMember(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToken(arg0: bigint): Promise<Token | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToken(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToken(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransitionRule(arg0: bigint): Promise<TransitionRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransitionRule(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransitionRule(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValidationRule(arg0: bigint): Promise<ValidationRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getValidationRule(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValidationRule(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleStripePaymentCompleted(arg0: SubscriptionTier, arg1: Principal): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.handleStripePaymentCompleted(to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleStripePaymentCompleted(to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssets();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssets();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssetsByProject(arg0: bigint): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssetsByProject(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssetsByProject(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCollectionsByProject(arg0: bigint): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollectionsByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollectionsByProject(arg0);
            return result;
        }
    }
    async listFileMetadataByAsset(arg0: bigint): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileMetadataByAsset(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileMetadataByAsset(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMembersByProject(arg0: bigint): Promise<Array<ProjectMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembersByProject(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembersByProject(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMergeOperationsByProject(arg0: bigint): Promise<Array<MergeOperation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMergeOperationsByProject(arg0);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMergeOperationsByProject(arg0);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTasksByProject(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByProject(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByProject(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTokensByProject(arg0: bigint): Promise<Array<Token>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTokensByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTokensByProject(arg0);
            return result;
        }
    }
    async listTransitionRulesByProject(arg0: bigint): Promise<Array<TransitionRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransitionRulesByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransitionRulesByProject(arg0);
            return result;
        }
    }
    async listValidationRulesByProject(arg0: bigint): Promise<Array<ValidationRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listValidationRulesByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listValidationRulesByProject(arg0);
            return result;
        }
    }
    async mintToken(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "Ok";
        Ok: Token;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.mintToken(arg0, arg1, arg2, arg3);
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintToken(arg0, arg1, arg2, arg3);
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async removeProjectMember(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProjectMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProjectMember(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async selfAssignAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selfAssignAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selfAssignAdmin();
            return result;
        }
    }
    async setPlatformConfig(arg0: PlatformConfig): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlatformConfig(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlatformConfig(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async storeFileMetadata(arg0: bigint, arg1: bigint | null, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeFileMetadata(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeFileMetadata(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAsset(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAsset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAsset(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCollection(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProjectMemberRole(arg0: bigint, arg1: Principal, arg2: ProjectRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectMemberRole(arg0, arg1, to_candid_ProjectRole_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async upgradeSubscription(arg0: SubscriptionTier): Promise<{
        __kind__: "Ok";
        Ok: null;
    } | {
        __kind__: "Err";
        Err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeSubscription(to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeSubscription(to_candid_SubscriptionTier_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Asset_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Asset): Asset {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_FileMetadata_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): FileMetadata {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MergeOperation_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MergeOperation): MergeOperation {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectMember_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectMember): ProjectMember {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectRole): ProjectRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserSubscription_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSubscription): UserSubscription {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMetadata]): FileMetadata | null {
    return value.length === 0 ? null : from_candid_FileMetadata_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MergeOperation]): MergeOperation | null {
    return value.length === 0 ? null : from_candid_MergeOperation_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSubscription]): UserSubscription | null {
    return value.length === 0 ? null : from_candid_UserSubscription_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlatformConfig]): PlatformConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectMember]): ProjectMember | null {
    return value.length === 0 ? null : from_candid_ProjectMember_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Token]): Token | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransitionRule]): TransitionRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ValidationRule]): ValidationRule | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Asset]): Asset | null {
    return value.length === 0 ? null : from_candid_Asset_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: [] | [_Time];
    projectId: bigint;
}): {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
    projectId: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.updatedAt)),
        projectId: value.projectId
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assetId: [] | [bigint];
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): {
    id: bigint;
    assetId?: bigint;
    hash: string;
    size: bigint;
    mimeType: string;
    filename: string;
    projectId: bigint;
    uploadedAt: bigint;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        assetId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assetId)),
        hash: value.hash,
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        projectId: value.projectId,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    completedAt: [] | [bigint];
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
}): {
    id: bigint;
    status: string;
    completedAt?: bigint;
    createdAt: bigint;
    createdBy: Principal;
    sourceAssetIds: Array<bigint>;
    targetAssetId: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        completedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.completedAt)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        sourceAssetIds: value.sourceAssetIds,
        targetAssetId: value.targetAssetId,
        projectId: value.projectId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    tier: _SubscriptionTier;
    updatedAt: bigint;
}): {
    principal: Principal;
    tier: SubscriptionTier;
    updatedAt: bigint;
} {
    return {
        principal: value.principal,
        tier: from_candid_SubscriptionTier_n27(_uploadFile, _downloadFile, value.tier),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: [] | [_Time];
}): {
    id: bigint;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt?: Time;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.updatedAt))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: Principal;
    role: _ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
}): {
    member: Principal;
    role: ProjectRole;
    addedAt: bigint;
    addedBy: Principal;
    projectId: bigint;
} {
    return {
        member: value.member,
        role: from_candid_ProjectRole_n36(_uploadFile, _downloadFile, value.role),
        addedAt: value.addedAt,
        addedBy: value.addedBy,
        projectId: value.projectId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    assignedTo: [] | [Principal];
    assetId: [] | [bigint];
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
}): {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    assetId?: bigint;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    description: string;
    updatedAt: bigint;
    projectId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        assignedTo: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.assignedTo)),
        assetId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assetId)),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: value.projectId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    starter: null;
} | {
    free: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "starter" in value ? SubscriptionTier.starter : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    editor: null;
} | {
    viewer: null;
}): ProjectRole {
    return "admin" in value ? ProjectRole.admin : "editor" in value ? ProjectRole.editor : "viewer" in value ? ProjectRole.viewer : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n40(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: bigint;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Ok: _Token;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: Token;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Asset>): Array<Asset> {
    return value.map((x)=>from_candid_Asset_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Array<FileMetadata> {
    return value.map((x)=>from_candid_FileMetadata_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectMember>): Array<ProjectMember> {
    return value.map((x)=>from_candid_ProjectMember_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MergeOperation>): Array<MergeOperation> {
    return value.map((x)=>from_candid_MergeOperation_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n43(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): _ProjectRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectRole): {
    admin: null;
} | {
    editor: null;
} | {
    viewer: null;
} {
    return value == ProjectRole.admin ? {
        admin: null
    } : value == ProjectRole.editor ? {
        editor: null
    } : value == ProjectRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    starter: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.starter ? {
        starter: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
